### ISSUE TITLE
Не работает notifications, что я делаю не так?

### ISSUE THREAD

**Issue by murattishkul** [vanyakosmos/travis-tg-notifier#4]
```
language: node_js
node_js:
  - "node"
notifications:
  webhooks:
    - https://travis-tg.herokuapp.com/u/-422708181/force
    - https://travis-tg.herokuapp.com/u/504816358/force

```

**Comment by vanyakosmos** [comment]
Используй код блоки в следующий раз:
````` 
```
foo:
  bar
```
````` 
Потому что сейчас похоже что вебхуки вообще не под полем `notifications`. Этот проект использует себя же для отправки уведомлений, так что можешь чукнуть пример в травис конфиге: https://github.com/vanyakosmos/travis-tg-notifier/blob/master/.travis.yml#L27-L29

То есть в твое случае должно быть как-то так:

```
notifications:
  webhooks:
    - https://travis-tg.herokuapp.com/u/-422708181/force
    - https://travis-tg.herokuapp.com/u/504816358/force
```

**Comment by murattishkul** [comment]
изменил на кодблоки

**Comment by vanyakosmos** [comment]
а бота ты добавлял в эти группы/чаты? чтоб у него были нужные пермишены для отправки тебе сообщений

**Comment by murattishkul** [comment]
добавил, а пермишены не знаю как задавать

**Comment by murattishkul** [comment]
все пермишны даны

**Comment by vanyakosmos** [comment]
Я уже давно сам не пользовался и решил проверить работает ли бот вообще. И вот перезапустил джобу с ПРом от депендабота и пришла уведомлялка что билд удачный.

<img width="430" alt="Screenshot 2020-07-11 at 18 29 53" src="https://user-images.githubusercontent.com/16745500/87227559-8c0df800-c3a4-11ea-924a-d6dce1e8dee9.png">

Так что расчехляй свои билды и проверяй идет ли что-то. Перепроверь айдишники группы/юзера, может в них траблы.

**Comment by murattishkul** [comment]
спасибо! как узнаю изза чего не робит, сообщу

**Comment by murattishkul** [comment]
билды идут, айдишки правильные, но у бота no access to messages
![image](https://user-images.githubusercontent.com/38204149/87230841-246fa100-c3d4-11ea-8f22-297eae6c4dcf.png)

**Comment by murattishkul** [comment]
может в этом проблема? как давать боту нужные access rights?

**Comment by vanyakosmos** [comment]
Не, что-то вот в логах вижу что неправильная сигнатура приходит в хедере запроса от трависа (она используется для проверки что сообщение на сервер бота было присланно именно трависом).

Я за 11 месяцев я уже призабыл детали, но вроде как могут быть проблемы с travis.com (для приватных реп). Я проверял работоспособность именно на travis.org (для публичных реп).

Я кажись даже представляю где может быть проблема. Но сначала нужно чтоб ты подтвердил что ты используешь именно travis.com

**Comment by murattishkul** [comment]
использую travis.com (не .org)

**Comment by vanyakosmos** [comment]
залил хотфикс, попробуй перезапустить блид.

![Screen Recording 2020-07-11 at 21 36 45](https://user-images.githubusercontent.com/16745500/87231302-c4223480-c3be-11ea-9750-e4c66af147da.gif)

**Comment by murattishkul** [comment]
Через 30 минут перезапущу

вс, 12 июля 2020 г. в 00:38, Bachynin Ivan <notifications@github.com>:

**Comment by murattishkul** [comment]
работает, большое спасибо за такую фичу)

**Comment by vanyakosmos** [comment]
аллилуйа
спасибо за найденный баг и кооперацию)
